app:
  name: springboot-base

spring:
  profiles.include: 'profile'
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: rkskekfk
    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: ./mapper
#  mybatis.type-aliases-package: com.example.project.domain
#  configuration:
#    default-statement-timeout: 30